# Generated by Django 4.0 on 2022-01-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingstaff',
            name='current_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='auths.subject'),
        ),
        migrations.AlterField(
            model_name='teachingstaff',
            name='other_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other', to='auths.subject'),
        ),
    ]
