# Generated by Django 4.0 on 2022-01-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_teachingstaff_current_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingstafffiles',
            options={'ordering': ('id',), 'verbose_name': 'Teaching Staff File', 'verbose_name_plural': 'Teaching Staff Files'},
        ),
        migrations.AddField(
            model_name='nonteachingstafffiles',
            name='document_title',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfiles',
            name='document_title',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nonteachingstaff',
            name='first_appointment',
            field=models.DateField(null=True),
        ),
    ]
