# Generated by Django 4.0 on 2021-12-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_teachingstafffiles_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingstafffiles',
            name='document_title',
        ),
    ]
