# Generated by Django 4.0 on 2022-01-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_teachingstafffiles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_img',
            field=models.ImageField(null=True, upload_to='Parents_Fathers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_img',
            field=models.ImageField(null=True, upload_to='Parents_Mothers/%Y/%m/%d/'),
        ),
    ]
