# Generated by Django 4.0 on 2022-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_student_admission_year_student_father_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=10, null=True, verbose_name="Father's Full Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_phone',
            field=models.CharField(max_length=10, null=True, verbose_name="Father's Phone Number"),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=10, null=True, verbose_name="Mother's Full Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_number',
            field=models.CharField(max_length=10, null=True, verbose_name="Mother's Phone Number"),
        ),
    ]
