# Generated by Django 4.0 on 2021-12-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_remove_teachingstafffiles_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingstafffiles',
            name='documents',
            field=models.FileField(upload_to='Non_Teachers_Files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='studentfiles',
            name='documents',
            field=models.FileField(upload_to='Student_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='teachingstafffiles',
            name='documents',
            field=models.FileField(upload_to='Teachers_Files/%Y/%m/%d/'),
        ),
    ]
