# Generated by Django 4.0 on 2022-01-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_student_father_name_alter_student_father_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mother_number',
            new_name='mother_phone',
        ),
    ]
